export {
  WECHAT_COMPONENT_ENDPOINTS,
  WechatComponentProviderAdapter,
  createWechatComponentAccessTokenResolver,
  createWechatComponentAdapter,
  createWechatComponentProvider,
  createWechatComponentProviderAdapter,
  createWechatOpenPlatformComponentAdapter,
  createWechatThirdPartyPlatformAdapter,
} from "./platforms.js";

export type {
  WechatApplicationSecretResolver,
  WechatApplicationSecretResolverInput,
  WechatComponentAppIdResolver,
  WechatComponentAppIdResolverInput,
  WechatComponentAccessTokenResolution,
  WechatComponentAccessTokenResolver,
  WechatComponentAccessTokenResolverOptions,
  WechatComponentAccessTokenResolverInput,
  WechatComponentAccessTokenResolverLike,
  WechatComponentAccessTokenResolverObject,
  WechatComponentAccessTokenResolverResult,
  WechatComponentAccountBinding,
  WechatComponentAccountBindingCollection,
  WechatComponentAccountBindingInput,
  WechatComponentAccountStatus,
  WechatComponentAdapterOptions,
  WechatComponentAuthorizedAccountBinding,
  WechatComponentBinding,
  WechatComponentBindingResolver,
  WechatComponentBindingResolverInput,
  WechatComponentBindingResolverLike,
  WechatComponentBindingResolverObject,
  WechatComponentEndpoints,
  WechatComponentProvider,
  WechatComponentProviderOptions,
  WechatComponentSecretSource,
  WechatComponentTokenMetadata,
  WechatComponentTokenResolver,
  WechatAuthorizedAccountBinding,
} from "./platforms.js";
