import { defineIdaasConfig } from "@getbrick/idaas-core";

export const idaas = defineIdaasConfig({
  appName: "Getbrick Example",
  session: { expiresInDays: 7, storeInDatabase: true },
  password: { minLength: 8 },
  features: { twoFactor: true, organization: true },
  oidc: {
    op: {
      enabled: true,
      issuer: "http://localhost:3000/oidc",
      basePath: "/oidc",
      loginURL: "http://localhost:3000/login",
      scopes: ["openid", "profile", "email", "offline_access"],
      clients: [
        {
          clientId: "getbrick-demo-client",
          clientName: "Getbrick Demo",
          redirectUris: ["http://localhost:3000/demo/callback"],
          scopes: ["openid", "profile", "email"],
        },
      ],
    },
  },
  rbac: {
    roles: {
      member: { extends: ["user"], permissions: ["project:read:own"] },
      owner: {
        extends: ["member"],
        permissions: [
          "project:write",
          "applications:read",
          "applications:write",
          "application-platforms:read",
          "application-platforms:write",
           "application-clients:read",
           "application-clients:write",
           "applications:validate",
           "applications:enable",
           "applications:disable",
           "applications:archive",
           "applications:restore",
           "applications:purge",
           "application-platforms:validate",
           "application-platforms:enable",
           "application-platforms:disable",
           "application-platforms:archive",
           "application-platforms:restore",
           "application-platforms:purge",
           "application-platforms:rotate-secret",
           "application-platforms:revoke-secret",
           "application-clients:validate",
           "application-clients:enable",
           "application-clients:disable",
           "application-clients:archive",
           "application-clients:restore",
           "application-clients:purge",
           "application-clients:rotate-secret",
           "application-clients:revoke-secret",
           "application-external-identities:read",
        ],
      },
    },
  },
});
